-- ============================================
-- HEALTHCARE ANALYTICS PROJECT
-- Step 1: Environment Setup
-- Author: Akshay Thakae
-- Date: 03 March 2026
-- ============================================

CREATE WAREHOUSE IF NOT EXISTS HEALTHCARE_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE DATABASE IF NOT EXISTS HEALTHCARE_DB;

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.CLEAN;
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_DB.ANALYTICS;
