-- ============================================
-- Step 4: ANALYTICS Layer
-- Pre-aggregated tables for Power BI
-- ============================================

USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE HEALTHCARE_DB.ANALYTICS.MONTHLY_ADMISSIONS AS
SELECT 
    ADMISSION_YEAR,
    ADMISSION_MONTH,
    ADMISSION_MONTH_NAME,
    COUNT(*)                            AS TOTAL_ADMISSIONS,
    ROUND(SUM(BILLING_AMOUNT), 2)       AS TOTAL_REVENUE,
    ROUND(AVG(BILLING_AMOUNT), 2)       AS AVG_BILLING,
    ROUND(AVG(LENGTH_OF_STAY_DAYS), 1)  AS AVG_STAY_DAYS
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY ADMISSION_YEAR, ADMISSION_MONTH, ADMISSION_MONTH_NAME;

CREATE OR REPLACE TABLE HEALTHCARE_DB.ANALYTICS.CONDITION_SUMMARY AS
SELECT 
    MEDICAL_CONDITION,
    COUNT(*)                            AS TOTAL_PATIENTS,
    ROUND(AVG(BILLING_AMOUNT), 2)       AS AVG_BILLING,
    ROUND(SUM(BILLING_AMOUNT), 2)       AS TOTAL_REVENUE,
    ROUND(AVG(LENGTH_OF_STAY_DAYS), 1)  AS AVG_STAY_DAYS,
    SUM(CASE WHEN TEST_RESULTS = 'Abnormal' THEN 1 ELSE 0 END) AS ABNORMAL_COUNT,
    ROUND(
        SUM(CASE WHEN TEST_RESULTS = 'Abnormal' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*), 2
    )                                   AS ABNORMAL_RATE_PCT
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY MEDICAL_CONDITION;

CREATE OR REPLACE TABLE HEALTHCARE_DB.ANALYTICS.INSURANCE_SUMMARY AS
SELECT 
    INSURANCE_PROVIDER,
    COUNT(*)                            AS TOTAL_PATIENTS,
    ROUND(SUM(BILLING_AMOUNT), 2)       AS TOTAL_REVENUE,
    ROUND(AVG(BILLING_AMOUNT), 2)       AS AVG_BILLING,
    ROUND(SUM(BILLING_AMOUNT) * 100.0 / 
        SUM(SUM(BILLING_AMOUNT)) OVER(), 2) AS REVENUE_SHARE_PCT
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY INSURANCE_PROVIDER;

CREATE OR REPLACE TABLE HEALTHCARE_DB.ANALYTICS.AGE_GROUP_SUMMARY AS
SELECT 
    AGE_GROUP,
    GENDER,
    COUNT(*)                            AS TOTAL_PATIENTS,
    ROUND(AVG(BILLING_AMOUNT), 2)       AS AVG_BILLING,
    ROUND(AVG(LENGTH_OF_STAY_DAYS), 1)  AS AVG_STAY_DAYS,
    MEDICAL_CONDITION,
    ADMISSION_TYPE
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY AGE_GROUP, GENDER, MEDICAL_CONDITION, ADMISSION_TYPE;
