-- ============================================
-- Step 5: Business Question SQL Queries
-- 10 queries showcasing key SQL skills
-- ============================================

-- Q1: Total Admissions by Month
SELECT 
    ADMISSION_YEAR, ADMISSION_MONTH_NAME, ADMISSION_MONTH,
    COUNT(*) AS TOTAL_ADMISSIONS
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY ADMISSION_YEAR, ADMISSION_MONTH_NAME, ADMISSION_MONTH
ORDER BY ADMISSION_YEAR, ADMISSION_MONTH;

-- Q2: Average Billing by Medical Condition
SELECT 
    MEDICAL_CONDITION,
    COUNT(*)                        AS TOTAL_PATIENTS,
    ROUND(AVG(BILLING_AMOUNT), 2)   AS AVG_BILLING,
    ROUND(MIN(BILLING_AMOUNT), 2)   AS MIN_BILLING,
    ROUND(MAX(BILLING_AMOUNT), 2)   AS MAX_BILLING
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY MEDICAL_CONDITION
ORDER BY AVG_BILLING DESC;

-- Q3: Top 10 Doctors by Patient Count
SELECT 
    DOCTOR_NAME,
    COUNT(*)                        AS TOTAL_PATIENTS,
    ROUND(AVG(BILLING_AMOUNT), 2)   AS AVG_BILLING_PER_PATIENT,
    ROUND(AVG(LENGTH_OF_STAY_DAYS)) AS AVG_STAY_DAYS
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY DOCTOR_NAME
ORDER BY TOTAL_PATIENTS DESC
LIMIT 10;

-- Q4: Avg Length of Stay by Condition & Admission Type
SELECT 
    MEDICAL_CONDITION, ADMISSION_TYPE,
    ROUND(AVG(LENGTH_OF_STAY_DAYS), 1) AS AVG_STAY_DAYS,
    MAX(LENGTH_OF_STAY_DAYS)            AS MAX_STAY_DAYS,
    MIN(LENGTH_OF_STAY_DAYS)            AS MIN_STAY_DAYS
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY MEDICAL_CONDITION, ADMISSION_TYPE
ORDER BY AVG_STAY_DAYS DESC;

-- Q5: Abnormal Test Results % by Condition
SELECT 
    MEDICAL_CONDITION,
    COUNT(*)                                                        AS TOTAL_PATIENTS,
    SUM(CASE WHEN TEST_RESULTS = 'Abnormal' THEN 1 ELSE 0 END)     AS ABNORMAL_COUNT,
    ROUND(
        SUM(CASE WHEN TEST_RESULTS = 'Abnormal' THEN 1 ELSE 0 END) * 100.0 
        / COUNT(*), 2
    )                                                               AS ABNORMAL_RATE_PCT
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY MEDICAL_CONDITION
ORDER BY ABNORMAL_RATE_PCT DESC;

-- Q6: Revenue by Insurance Provider (with Window Function)
SELECT 
    INSURANCE_PROVIDER,
    COUNT(*)                                AS TOTAL_PATIENTS,
    ROUND(SUM(BILLING_AMOUNT), 2)           AS TOTAL_REVENUE,
    ROUND(AVG(BILLING_AMOUNT), 2)           AS AVG_REVENUE_PER_PATIENT,
    ROUND(SUM(BILLING_AMOUNT) * 100.0 / 
        SUM(SUM(BILLING_AMOUNT)) OVER(), 2) AS REVENUE_SHARE_PCT
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY INSURANCE_PROVIDER
ORDER BY TOTAL_REVENUE DESC;

-- Q7: Patient Age Group & Gender Breakdown
SELECT 
    AGE_GROUP, GENDER,
    COUNT(*)                        AS TOTAL_PATIENTS,
    ROUND(AVG(BILLING_AMOUNT), 2)   AS AVG_BILLING,
    ROUND(AVG(LENGTH_OF_STAY_DAYS)) AS AVG_STAY_DAYS
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY AGE_GROUP, GENDER
ORDER BY AGE_GROUP, GENDER;

-- Q8: Monthly Revenue Trend with Running Total (Window Function)
SELECT 
    ADMISSION_YEAR, ADMISSION_MONTH_NAME, ADMISSION_MONTH,
    ROUND(SUM(BILLING_AMOUNT), 2)   AS MONTHLY_REVENUE,
    ROUND(SUM(SUM(BILLING_AMOUNT)) 
        OVER (ORDER BY ADMISSION_YEAR, ADMISSION_MONTH), 2) AS RUNNING_TOTAL_REVENUE
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY ADMISSION_YEAR, ADMISSION_MONTH_NAME, ADMISSION_MONTH
ORDER BY ADMISSION_YEAR, ADMISSION_MONTH;

-- Q9: Admission Type Analysis
SELECT 
    ADMISSION_TYPE, MEDICAL_CONDITION,
    COUNT(*)                            AS TOTAL_PATIENTS,
    ROUND(AVG(BILLING_AMOUNT), 2)       AS AVG_BILLING,
    ROUND(AVG(LENGTH_OF_STAY_DAYS), 1)  AS AVG_STAY_DAYS,
    ROUND(COUNT(*) * 100.0 / 
        SUM(COUNT(*)) OVER(), 2)        AS PCT_OF_TOTAL
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
GROUP BY ADMISSION_TYPE, MEDICAL_CONDITION
ORDER BY TOTAL_PATIENTS DESC;

-- Q10: ❄️ Snowflake Time Travel — Data Recovery Demo
DELETE FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
WHERE MEDICAL_CONDITION = 'Diabetes';

SELECT COUNT(*) AS ROWS_AFTER_DELETE 
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS;

SELECT COUNT(*) AS ROWS_BEFORE_DELETE
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
    AT (OFFSET => -120);

INSERT INTO HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
SELECT * FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS
    AT (OFFSET => -120)
WHERE MEDICAL_CONDITION = 'Diabetes';

SELECT COUNT(*) AS ROWS_RESTORED 
FROM HEALTHCARE_DB.CLEAN.PATIENT_ADMISSIONS;
